### PR TITLE
Add better defaults than null

### PR DESCRIPTION
**Pull request by Pablete1234**
Stuff that should never happen, but just in case.

### CODE REVIEW

**Comment by twizmwazin** [comment]
In the case of the default spawn, I agree to make a default at 0,0, however there should also be a module error logged.

For the match thread, I disagree. Returning the first match thread may lead to confusion, thinking that the query was successful, even though it failed. It would be better to implement that "fix" on the end where it would be used, if it is appropriate.

**Comment by Pablete1234** [comment]
@twizmwazin The thing is a player should always be on a match thread, if it gets to return null, it means the player either just joined (and didn't get a match thread assigned yet) or is leaving (and was already removed from the match thread) and both are wierd cases, that would lead to npe's, this is an easy fix

**Comment by twizmwazin** [comment]
It prevents NPEs, but it may also lead to false conclusions. What if the player wasn't on the first match thread, for instance? (when leaving)

**Comment by Pablete1234** [comment]
@twizmwazin then probably a bug will occur, where the player will be gone and the match thread (second one or whatever) won't know the player left, it will create a bug, but it would be worse to have a npe, the bug we can fix, but it still will only happen with more than one match thread

**Comment by twizmwazin** [comment]
An NPE is a signal that something is broken and needs to be fixed. Exceptions are a language feature, not a tool designed by Sun to annoy you. By substituting a take value, you are asking for issues to be created, issues that wouldbbe difficult to debug.

**Comment by Pablete1234** [comment]
Should we throw an invalid state exception? It really should't ever happen that a player is checked when he has no match thread asigned, so i guess we should throw an invalid state exception?

**Comment by twizmwazin** [comment]
merged

**Pull request closed without merging**
